const WRITING_PROMPTS = [
{week:1, type:"Narrative", prompt:"Imagine driving a driverless car. Write a narrative describing your experience. Include details about where you drove and what happened on the drive."},
{week:2, type:"Narrative", prompt:"Imagine you own a smart home. Describe your home, including all of the cool features, who you like to hang out with in your home, and what things you like to do in the home."},
{week:3, type:"Informative/Explanatory", prompt:"Think about the cone snail. Write an informative/explanatory paragraph about the cone snail. Include facts about what its personality is like and what it eats."},
{week:4, type:"Informative/Explanatory", prompt:"Think about the blue-ringed octopus. Write an informative/explanatory paragraph about the blue-ringed octopus. Include facts about what its personality is like."},
{week:5, type:"Opinion", prompt:"Some people believe in the yeti, and some people don’t. Write an opinion paragraph describing how you feel about people continuing to spend time and money looking for the monster."},
{week:6, type:"Opinion", prompt:"Some people believe in the Loch Ness Monster, and some people don’t. Write an opinion paragraph describing how you feel about people continuing to spend time and money looking for the monster."},
{week:7, type:"Opinion", prompt:"Do you like haunted houses? What is your opinion on this Halloween tradition? Write an opinion paragraph in which you argue to keep the haunted houses or not."},
{week:8, type:"Opinion", prompt:"Do you like trick or treating? What is your opinion on this Halloween tradition? Write an opinion paragraph in which you argue to keep the tradition or start a new one."},
{week:9, type:"Informative/Explanatory", prompt:"Think about the campaigning process. Write an informative/explanatory paragraph about the steps in the campaigning process. Include facts about who campaigns and how they campaign."},
{week:10, type:"Informative/Explanatory", prompt:"Think about the voting process. Write an informative/explanatory paragraph about the steps in the voting process. Include facts about who can vote and how people vote."},
{week:11, type:"Narrative", prompt:"Imagine you are cliff camping for the first time. Describe your cliff camping experience. Include details about where you camped, who you camped with, and how you felt."},
{week:12, type:"Narrative", prompt:"Imagine you are skydiving for the first time. Describe your skydiving experience. Include details about where you dove, who was with you, and how you felt as you stepped out of the plane."},
{week:13, type:"Narrative", prompt:"Imagine you are on a tour to learn about a Mars rover. Write a narrative paragraph about what happens on the tour. Include details about what you learn about the rover."},
{week:14, type:"Narrative", prompt:"Imagine you are traveling on Orion. Write a narrative paragraph about what the spacecraft is like. Include details about who you are on it with and what happens during your travels."},
{week:15, type:"Informative/Explanatory", prompt:"Think about the long lost Atlantis. Write an informative/explanatory paragraph about Atlantis. Include details about what people think happened to the place."},
{week:16, type:"Informative/Explanatory", prompt:"Think about Amelia Earhart. Write an informative/explanatory paragraph about her last flight. Include details about where the flight took place and what happened after she disappeared."},
{week:17, type:"Opinion", prompt:"Do you think people should eat healthy? Write an opinion paragraph about whether people should eat healthy or not. Include details to support your opinion."},
{week:18, type:"Opinion", prompt:"Do you think people should exercise? Write an opinion paragraph about whether or not people should exercise. Include details to support your opinion."},
{week:19, type:"Informative/Explanatory", prompt:"Write an informative/explanatory paragraph about the Montgomery Bus Boycott. Include facts about what happened and who was involved."},
{week:20, type:"Informative/Explanatory", prompt:"Write an informative/explanatory paragraph about the 1963 March on Washington. Include facts about what happened and who was involved."},
{week:21, type:"Opinion", prompt:"Do you think George Washington was a good president? Write an opinion paragraph about him. Include reasons for why you do or do not think he was a good president."},
{week:22, type:"Opinion", prompt:"Do you think Abraham Lincoln was a good president? Write an opinion paragraph about him. Include reasons for why you do or do not think he was a good president."},
{week:23, type:"Informative/Explanatory", prompt:"Write an informative/explanatory paragraph about Lois Lowry. Include facts about her life, including her accomplishments."},
{week:24, type:"Informative/Explanatory", prompt:"Write an informative/explanatory paragraph about J.K. Rowling. Include facts about her life, including her accomplishments."},
{week:25, type:"Narrative", prompt:"Imagine you are experiencing your first heat wave. Write a narrative paragraph describing your experience. Include details about what you do to cool off."},
{week:26, type:"Narrative", prompt:"Imagine you are trapped in a blizzard. Write a narrative paragraph describing your experience."},
{week:27, type:"Opinion", prompt:"How do you feel about Robert Frost’s poem? Write an opinion paragraph about your thoughts. Include details to support your opinion."},
{week:28, type:"Opinion", prompt:"How do you feel about Emily Dickinson’s poem? Write an opinion paragraph about your thoughts. Include details to support your opinion."},
{week:29, type:"Narrative", prompt:"Write a narrative paragraph about recycling. Include a specific character who recycles and why he or she does it."},
{week:30, type:"Narrative", prompt:"Write a narrative paragraph about saving energy. Include a specific character who saves energy and how he or she does it."},
{week:31, type:"Informative/Explanatory", prompt:"Write an informative/explanatory paragraph about tsunamis. Include facts about what a tsunami is, how it begins, and what types of destruction it can cause."},
{week:32, type:"Informative/Explanatory", prompt:"Write an informative/explanatory paragraph about avalanches. Include facts about what an avalanche is, how it begins, and what types of destruction it can cause."},
{week:33, type:"Opinion", prompt:"Do you like rides at amusement parks? Write an opinion paragraph describing which amusement park has the best rides. Include details to support your opinion."},
{week:34, type:"Opinion", prompt:"Do you like the food served at amusement parks? Write an opinion paragraph describing how you feel about amusement-park food. Include details to support your opinion."},
{week:35, type:"Narrative", prompt:"Write a narrative describing some summer activities you enjoy. Include details about who you do the activities with and where you like to do them."},
{week:36, type:"Narrative", prompt:"Write a narrative describing your favorite vacation. Include details about where you went, who you went with, and the events that occurred while you were on the trip."},
];
